# Generated by Django 3.2.7 on 2021-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoption',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='audience_insights_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_insights_update',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='trust_score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='promopackage',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
