# Generated by Django 3.2.7 on 2021-09-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210914_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoption',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='audience_insights_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_insights_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='trust_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='promopackage',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
