# Generated by Django 3.2.7 on 2021-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210914_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
