# Generated by Django 3.2.7 on 2021-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoption',
            name='price',
            field=models.FloatField(),
        ),
    ]
