# Generated by Django 3.2.7 on 2021-09-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_rename_price_packageoption_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoption',
            name='package_id',
            field=models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, to='pages.promopackage'),
        ),
        migrations.AlterField(
            model_name='page',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promo',
            name='client_id',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promo',
            name='option_id',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, to='pages.packageoption'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='package_id',
            field=models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, to='pages.promopackage'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='page_id',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.AlterField(
            model_name='promopackage',
            name='page_id',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
    ]
