# Generated by Django 3.2.7 on 2021-09-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210915_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='package_id',
        ),
        migrations.AddField(
            model_name='packageoption',
            name='option_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='package_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='page_id',
            field=models.ForeignKey(db_column='page_id', default=3, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='PromoPackage',
        ),
    ]
