# Generated by Django 3.2.7 on 2021-09-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210917_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageoption',
            old_name='posts',
            new_name='posts_amount',
        ),
        migrations.RenameField(
            model_name='packageoption',
            old_name='post_price',
            new_name='price_per_post',
        ),
    ]
