# Generated by Django 3.2.7 on 2021-09-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_packageoption_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoption',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
