# Generated by Django 3.2.7 on 2021-09-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_packageoption_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageoption',
            old_name='discount',
            new_name='price_discounted',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='posts_amount',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='price_per_post',
        ),
        migrations.AddField(
            model_name='packageoption',
            name='package_data',
            field=models.JSONField(default={'test': 1}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageoption',
            name='price_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='price_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(max_length=15)),
                ('goal', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('page_id', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(max_length=15)),
                ('discount_data', models.JSONField()),
                ('page_id', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
    ]
