# Generated by Django 3.2.7 on 2021-09-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210918_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
        migrations.RenameModel(
            old_name='PostAvailable',
            new_name='PagePost',
        ),
    ]
