# Generated by Django 3.2.7 on 2021-09-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210918_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('amount', models.IntegerField()),
                ('discounted_post_goal', models.CharField(max_length=15)),
                ('discounted_post_placement', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(blank=True, max_length=15, null=True)),
                ('package_type', models.CharField(max_length=15)),
                ('price_total', models.FloatField(blank=True, null=True)),
                ('price_discounted', models.FloatField(blank=True, null=True)),
                ('price_final', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_amount', models.IntegerField()),
                ('package_id', models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, to='pages.package')),
            ],
        ),
        migrations.RenameModel(
            old_name='PagePost',
            new_name='Post',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='page_id',
        ),
        migrations.AddField(
            model_name='page',
            name='bundle_discount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='postpackage',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.AddField(
            model_name='package',
            name='page_id',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.AddField(
            model_name='bulkdiscount',
            name='page_id',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='option_id',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, to='pages.package'),
        ),
        migrations.DeleteModel(
            name='PackageOption',
        ),
    ]
